name: test
on:
  push:
    branches:
      - main
      # - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Test with docker-compose stack
      #   run: |
      #     docker-compose up -d --remove-orphans
      #     docker exec app go test -cover -v ./...
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: echo
        run: echo ${{ secrets.LOG_FILE_PATH }}
      - name: exoprt
        run: export TEST_LOG_FILE_PATH=${{ secrets.LOG_FILE_PATH }}
      - name: exoprt_read
        run: echo $TEST_LOG_FILE_PATH
      
          
          
        