name: test
on:
  push:
    branches:
      - main
      # - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Test with docker-compose stack
      #   run: |
      #     docker-compose up -d --remove-orphans
      #     docker exec app go test -cover -v ./...
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: echo
        run: echo ${{ secrets.LOG_FILE_PATH }}
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.LOG_FILE_PATH }}
        run:
          export LOG_FILE_PATH="$SUPER_SECRET" 
      - name: e
        run:
          echo $LOG_FILE_PATH
          
          