name: test
on:
  push:
    branches:
      - main
      # - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with docker-compose stack
        run: |
          docker-compose build
          docker-compose up -d --remove-orphans
          docker exec app go test -cover -v ./...